package constants

// Package constants holds LinkedIn static lookup tables that were provided by
// the original Python implementation in `linkedin_constants.py`.  Keeping them
// here allows services (e.g. the LinkedIn immediate-processor) to perform the
// same URN→human-readable mapping without re-implementing logic each time.
//
// NOTE:  Only a subset of mappings that we actively use today are included
// below.  You can safely extend these maps at build-time without touching any
// consuming code, because the accessors (`GetSeniorities`, `GetIndustries`,
// `GetCountries`) always return the underlying map by value.

// seniorities maps LinkedIn URNs for seniority levels to human-readable names.
var seniorities = map[string]string{
    "urn:li:seniority:1":  "Training",
    "urn:li:seniority:2":  "Entry",
    "urn:li:seniority:3":  "Associate",
    "urn:li:seniority:4":  "Mid-Senior",
    "urn:li:seniority:5":  "Director",
    "urn:li:seniority:6":  "Executive",
    "urn:li:seniority:7":  "Partner",
    "urn:li:seniority:8":  "Manager",
    "urn:li:seniority:9":  "Intern",
    "urn:li:seniority:10": "Volunteer",
    "urn:li:seniority:11": "Temporary",
}

// industries maps LinkedIn URNs for industries to human-readable names.
var industries = map[string]string{
    "urn:li:industry:1": "Defense & Space",
	"urn:li:industry:3": "Computer Hardware",
	"urn:li:industry:4": "Computer Software",
	"urn:li:industry:5": "Computer Networking",
	"urn:li:industry:6": "Internet",
	"urn:li:industry:7": "Semiconductors",
	"urn:li:industry:8": "Telecommunications",
	"urn:li:industry:9": "Law Practice",
	"urn:li:industry:10": "Legal Services",
	"urn:li:industry:11": "Management Consulting",
	"urn:li:industry:12": "Biotechnology",
	"urn:li:industry:13": "Medical Practice",
	"urn:li:industry:14": "Hospital & Health Care",
	"urn:li:industry:15": "Pharmaceuticals",
	"urn:li:industry:16": "Veterinary",
	"urn:li:industry:17": "Medical Device",
	"urn:li:industry:18": "Cosmetics",
	"urn:li:industry:19": "Apparel & Fashion",
	"urn:li:industry:20": "Sporting Goods",
	"urn:li:industry:21": "Tobacco",
	"urn:li:industry:22": "Supermarkets",
	"urn:li:industry:23": "Food Production",
	"urn:li:industry:24": "Consumer Electronics",
	"urn:li:industry:25": "Consumer Goods",
	"urn:li:industry:26": "Furniture",
	"urn:li:industry:27": "Retail",
	"urn:li:industry:28": "Entertainment",
	"urn:li:industry:29": "Gambling & Casinos",
	"urn:li:industry:30": "Leisure, Travel & Tourism",
	"urn:li:industry:31": "Hospitality",
	"urn:li:industry:32": "Restaurants",
	"urn:li:industry:33": "Sports",
	"urn:li:industry:34": "Food & Beverages",
	"urn:li:industry:35": "Motion Pictures & Film",
	"urn:li:industry:36": "Broadcast Media",
	"urn:li:industry:37": "Museums & Institutions",
	"urn:li:industry:38": "Fine Art",
	"urn:li:industry:39": "Performing Arts",
	"urn:li:industry:40": "Recreational Facilities & Services",
	"urn:li:industry:41": "Banking",
	"urn:li:industry:42": "Insurance",
	"urn:li:industry:43": "Financial Services",
	"urn:li:industry:44": "Real Estate",
	"urn:li:industry:45": "Investment Banking",
	"urn:li:industry:46": "Investment Management",
	"urn:li:industry:47": "Accounting",
	"urn:li:industry:48": "Construction",
	"urn:li:industry:49": "Building Materials",
	"urn:li:industry:50": "Architecture & Planning",
	"urn:li:industry:51": "Civil Engineering",
	"urn:li:industry:52": "Aviation & Aerospace",
	"urn:li:industry:53": "Automotive",
	"urn:li:industry:54": "Chemicals",
	"urn:li:industry:55": "Machinery",
	"urn:li:industry:56": "Mining & Metals",
	"urn:li:industry:57": "Oil & Energy",
	"urn:li:industry:58": "Shipbuilding",
	"urn:li:industry:59": "Utilities",
	"urn:li:industry:3131": "Mobile Games",
	"urn:li:industry:60": "Textiles",
	"urn:li:industry:61": "Paper & Forest Products",
	"urn:li:industry:62": "Railroad Manufacture",
	"urn:li:industry:63": "Farming",
	"urn:li:industry:64": "Ranching",
	"urn:li:industry:65": "Dairy",
	"urn:li:industry:66": "Fishery",
	"urn:li:industry:67": "Primary/Secondary Education",
	"urn:li:industry:68": "Higher Education",
	"urn:li:industry:69": "Education Management",
	"urn:li:industry:70": "Research",
	"urn:li:industry:71": "Military",
	"urn:li:industry:72": "Legislative Office",
	"urn:li:industry:73": "Judiciary",
	"urn:li:industry:74": "International Affairs",
	"urn:li:industry:75": "Government Administration",
	"urn:li:industry:76": "Executive Office",
	"urn:li:industry:77": "Law Enforcement",
	"urn:li:industry:78": "Public Safety",
	"urn:li:industry:79": "Public Policy",
	"urn:li:industry:80": "Marketing & Advertising",
	"urn:li:industry:81": "Newspapers",
	"urn:li:industry:82": "Publishing",
	"urn:li:industry:83": "Printing",
	"urn:li:industry:84": "Information Services",
	"urn:li:industry:85": "Libraries",
	"urn:li:industry:86": "Environmental Services",
	"urn:li:industry:87": "Package/Freight Delivery",
	"urn:li:industry:88": "Individual & Family Services",
	"urn:li:industry:89": "Religious Institutions",
	"urn:li:industry:90": "Civic & Social Organization",
	"urn:li:industry:91": "Consumer Services",
	"urn:li:industry:92": "Transportation/Trucking/Railroad",
	"urn:li:industry:93": "Warehousing",
	"urn:li:industry:94": "Airlines/Aviation",
	"urn:li:industry:95": "Maritime",
	"urn:li:industry:96": "Information Technology & Services",
	"urn:li:industry:97": "Market Research",
	"urn:li:industry:98": "Public Relations & Communications",
	"urn:li:industry:99": "Design",
	"urn:li:industry:100": "Non-profit Organization Management",
	"urn:li:industry:101": "Fundraising",
	"urn:li:industry:102": "Program Development",
	"urn:li:industry:103": "Writing & Editing",
	"urn:li:industry:104": "Staffing & Recruiting",
	"urn:li:industry:105": "Professional Training & Coaching",
	"urn:li:industry:106": "Venture Capital & Private Equity",
	"urn:li:industry:107": "Political Organization",
	"urn:li:industry:108": "Translation & Localization",
	"urn:li:industry:109": "Computer Games",
	"urn:li:industry:110": "Events Services",
	"urn:li:industry:111": "Arts & Crafts",
	"urn:li:industry:112": "Electrical & Electronic Manufacturing",
	"urn:li:industry:113": "Online Media",
	"urn:li:industry:114": "Nanotechnology",
	"urn:li:industry:115": "Music",
	"urn:li:industry:116": "Logistics & Supply Chain",
	"urn:li:industry:117": "Plastics",
	"urn:li:industry:118": "Computer & Network Security",
	"urn:li:industry:119": "Wireless",
	"urn:li:industry:120": "Alternative Dispute Resolution",
	"urn:li:industry:121": "Security & Investigations",
	"urn:li:industry:122": "Facilities Services",
	"urn:li:industry:123": "Outsourcing/Offshoring",
	"urn:li:industry:124": "Health, Wellness & Fitness",
	"urn:li:industry:125": "Alternative Medicine",
	"urn:li:industry:126": "Media Production",
	"urn:li:industry:127": "Animation",
	"urn:li:industry:128": "Commercial Real Estate",
	"urn:li:industry:129": "Capital Markets",
	"urn:li:industry:130": "Think Tanks",
	"urn:li:industry:131": "Philanthropy",
	"urn:li:industry:132": "E-learning",
	"urn:li:industry:133": "Wholesale",
	"urn:li:industry:134": "Import & Export",
	"urn:li:industry:135": "Mechanical Or Industrial Engineering",
	"urn:li:industry:136": "Photography",
	"urn:li:industry:137": "Human Resources",
	"urn:li:industry:138": "Business Supplies & Equipment",
	"urn:li:industry:139": "Mental Health Care",
	"urn:li:industry:140": "Graphic Design",
	"urn:li:industry:141": "International Trade & Development",
	"urn:li:industry:142": "Wine & Spirits",
	"urn:li:industry:143": "Luxury Goods & Jewelry",
	"urn:li:industry:144": "Renewables & Environment",
	"urn:li:industry:145": "Glass, Ceramics & Concrete",
	"urn:li:industry:146": "Packaging & Containers",
	"urn:li:industry:147": "Industrial Automation",
	"urn:li:industry:148": "Government Relations",
	"urn:li:industry:149": "Unknown",
	"urn:li:industry:150": "Horticulture",
}

// countries maps LinkedIn URNs for ISO-3166 country codes to country names.
var countries = map[string]string{
    "urn:li:country:ad": "Andorra",
	"urn:li:country:ae": "United Arab Emirates",
	"urn:li:country:af": "Afghanistan",
	"urn:li:country:ag": "Antigua and Barbuda",
	"urn:li:country:ai": "Anguilla",
	"urn:li:country:al": "Albania",
	"urn:li:country:am": "Armenia",
	"urn:li:country:an": "Netherlands Antilles",
	"urn:li:country:ao": "Angola",
	"urn:li:country:aq": "Antarctica",
	"urn:li:country:ar": "Argentina",
	"urn:li:country:as": "American Samoa",
	"urn:li:country:at": "Austria",
	"urn:li:country:au": "Australia",
	"urn:li:country:aw": "Aruba",
	"urn:li:country:ax": "Aland Islands",
	"urn:li:country:az": "Azerbaijan",
	"urn:li:country:ba": "Bosnia and Herzegovina",
	"urn:li:country:bb": "Barbados",
	"urn:li:country:bd": "Bangladesh",
	"urn:li:country:be": "Belgium",
	"urn:li:country:bf": "Burkina Faso",
	"urn:li:country:bg": "Bulgaria",
	"urn:li:country:bh": "Bahrain",
	"urn:li:country:bi": "Burundi",
	"urn:li:country:bj": "Benin",
	"urn:li:country:bm": "Bermuda",
	"urn:li:country:bn": "Brunei Darussalam",
	"urn:li:country:bo": "Bolivia",
	"urn:li:country:br": "Brazil",
	"urn:li:country:bs": "Bahamas",
	"urn:li:country:bt": "Bhutan",
	"urn:li:country:bv": "Bouvet Island",
	"urn:li:country:bw": "Botswana",
	"urn:li:country:by": "Belarus",
	"urn:li:country:bz": "Belize",
	"urn:li:country:ca": "Canada",
	"urn:li:country:cb": "Caribbean Nations",
	"urn:li:country:cc": "Cocos (Keeling) Islands",
	"urn:li:country:cd": "Democratic Republic of the Congo",
	"urn:li:country:cf": "Central African Republic",
	"urn:li:country:cg": "Congo",
	"urn:li:country:ch": "Switzerland",
	"urn:li:country:ci": "Cote D\u2019Ivoire (Ivory Coast)",
	"urn:li:country:ck": "Cook Islands",
	"urn:li:country:cl": "Chile",
	"urn:li:country:cm": "Cameroon",
	"urn:li:country:cn": "China",
	"urn:li:country:co": "Colombia",
	"urn:li:country:cr": "Costa Rica",
	"urn:li:country:cs": "Serbia and Montenegro",
	"urn:li:country:cu": "Cuba",
	"urn:li:country:cv": "Cape Verde",
	"urn:li:country:cx": "Christmas Island",
	"urn:li:country:cy": "Cyprus",
	"urn:li:country:cz": "Czech Republic",
	"urn:li:country:de": "Germany",
	"urn:li:country:dj": "Djibouti",
	"urn:li:country:dk": "Denmark",
	"urn:li:country:dm": "Dominica",
	"urn:li:country:do": "Dominican Republic",
	"urn:li:country:dz": "Algeria",
	"urn:li:country:ec": "Ecuador",
	"urn:li:country:ee": "Estonia",
	"urn:li:country:eg": "Egypt",
	"urn:li:country:eh": "Western Sahara",
	"urn:li:country:er": "Eritrea",
	"urn:li:country:es": "Spain",
	"urn:li:country:et": "Ethiopia",
	"urn:li:country:fi": "Finland",
	"urn:li:country:fj": "Fiji",
	"urn:li:country:fk": "Falkland Islands (Malvinas)",
	"urn:li:country:fm": "Federated States of Micronesia",
	"urn:li:country:fo": "Faroe Islands",
	"urn:li:country:fr": "France",
	"urn:li:country:ga": "Gabon",
	"urn:li:country:gb": "United Kingdom",
	"urn:li:country:gd": "Grenada",
	"urn:li:country:ge": "Georgia",
	"urn:li:country:gf": "French Guiana",
	"urn:li:country:gg": "Guernsey",
	"urn:li:country:gh": "Ghana",
	"urn:li:country:gi": "Gibraltar",
	"urn:li:country:gl": "Greenland",
	"urn:li:country:gm": "Gambia",
	"urn:li:country:gn": "Guinea",
	"urn:li:country:gp": "Guadeloupe",
	"urn:li:country:gq": "Equatorial Guinea",
	"urn:li:country:gr": "Greece",
	"urn:li:country:gs": "S. Georgia and S. Sandwich Islands",
	"urn:li:country:gt": "Guatemala",
	"urn:li:country:gu": "Guam",
	"urn:li:country:gw": "Guinea-Bissau",
	"urn:li:country:gy": "Guyana",
	"urn:li:country:hk": "Hong Kong",
	"urn:li:country:hm": "Heard Island and McDonald Islands",
	"urn:li:country:hn": "Honduras",
	"urn:li:country:hr": "Croatia",
	"urn:li:country:ht": "Haiti",
	"urn:li:country:hu": "Hungary",
	"urn:li:country:id": "Indonesia",
	"urn:li:country:ie": "Ireland",
	"urn:li:country:il": "Israel",
	"urn:li:country:im": "Isle of Man",
	"urn:li:country:in": "India",
	"urn:li:country:io": "British Indian Ocean Territory",
	"urn:li:country:iq": "Iraq",
	"urn:li:country:ir": "Iran",
	"urn:li:country:is": "Iceland",
	"urn:li:country:it": "Italy",
	"urn:li:country:je": "Jersey",
	"urn:li:country:jm": "Jamaica",
	"urn:li:country:jo": "Jordan",
	"urn:li:country:jp": "Japan",
	"urn:li:country:ke": "Kenya",
	"urn:li:country:kg": "Kyrgyzstan",
	"urn:li:country:kh": "Cambodia",
	"urn:li:country:ki": "Kiribati",
	"urn:li:country:km": "Comoros",
	"urn:li:country:kn": "Saint Kitts and Nevis",
	"urn:li:country:ko": "Kosovo",
	"urn:li:country:kp": "Korea (North)",
	"urn:li:country:kr": "Korea",
	"urn:li:country:kw": "Kuwait",
	"urn:li:country:ky": "Cayman Islands",
	"urn:li:country:kz": "Kazakhstan",
	"urn:li:country:la": "Laos",
	"urn:li:country:lb": "Lebanon",
	"urn:li:country:lc": "Saint Lucia",
	"urn:li:country:li": "Liechtenstein",
	"urn:li:country:lk": "Sri Lanka",
	"urn:li:country:lr": "Liberia",
	"urn:li:country:ls": "Lesotho",
	"urn:li:country:lt": "Lithuania",
	"urn:li:country:lu": "Luxembourg",
	"urn:li:country:lv": "Latvia",
	"urn:li:country:ly": "Libya",
	"urn:li:country:ma": "Morocco",
	"urn:li:country:mc": "Monaco",
	"urn:li:country:md": "Moldova",
	"urn:li:country:me": "Montenegro",
	"urn:li:country:mg": "Madagascar",
	"urn:li:country:mh": "Marshall Islands",
	"urn:li:country:mk": "Macedonia",
	"urn:li:country:ml": "Mali",
	"urn:li:country:mm": "Myanmar",
	"urn:li:country:mn": "Mongolia",
	"urn:li:country:mo": "Macao",
	"urn:li:country:mp": "Northern Mariana Islands",
	"urn:li:country:mq": "Martinique",
	"urn:li:country:mr": "Mauritania",
	"urn:li:country:ms": "Montserrat",
	"urn:li:country:mt": "Malta",
	"urn:li:country:mu": "Mauritius",
	"urn:li:country:mv": "Maldives",
	"urn:li:country:mw": "Malawi",
	"urn:li:country:mx": "Mexico",
	"urn:li:country:my": "Malaysia",
	"urn:li:country:mz": "Mozambique",
	"urn:li:country:na": "Namibia",
	"urn:li:country:nc": "New Caledonia",
	"urn:li:country:ne": "Niger",
	"urn:li:country:nf": "Norfolk Island",
	"urn:li:country:ng": "Nigeria",
	"urn:li:country:ni": "Nicaragua",
	"urn:li:country:nl": "Netherlands",
	"urn:li:country:no": "Norway",
	"urn:li:country:np": "Nepal",
	"urn:li:country:nr": "Nauru",
	"urn:li:country:nu": "Niue",
	"urn:li:country:nz": "New Zealand",
	"urn:li:country:om": "Sultanate of Oman",
	"urn:li:country:oo": "Other",
	"urn:li:country:pa": "Panama",
	"urn:li:country:pe": "Peru",
	"urn:li:country:pf": "French Polynesia",
	"urn:li:country:pg": "Papua New Guinea",
	"urn:li:country:ph": "Philippines",
	"urn:li:country:pk": "Pakistan",
	"urn:li:country:pl": "Poland",
	"urn:li:country:pm": "Saint Pierre and Miquelon",
	"urn:li:country:pn": "Pitcairn",
	"urn:li:country:pr": "Puerto Rico",
	"urn:li:country:ps": "Palestinian Territory",
	"urn:li:country:pt": "Portugal",
	"urn:li:country:pw": "Palau",
	"urn:li:country:py": "Paraguay",
	"urn:li:country:qa": "Qatar",
	"urn:li:country:re": "Reunion",
	"urn:li:country:ro": "Romania",
	"urn:li:country:rs": "Serbia",
	"urn:li:country:ru": "Russian Federation",
	"urn:li:country:rw": "Rwanda",
	"urn:li:country:sa": "Saudi Arabia",
	"urn:li:country:sb": "Solomon Islands",
	"urn:li:country:sc": "Seychelles",
	"urn:li:country:sd": "Sudan",
	"urn:li:country:se": "Sweden",
	"urn:li:country:sg": "Singapore",
	"urn:li:country:sh": "Saint Helena",
	"urn:li:country:si": "Slovenia",
	"urn:li:country:sj": "Svalbard and Jan Mayen",
	"urn:li:country:sk": "Slovak Republic",
	"urn:li:country:sl": "Sierra Leone",
	"urn:li:country:sm": "San Marino",
	"urn:li:country:sn": "Senegal",
	"urn:li:country:so": "Somalia",
	"urn:li:country:sr": "Suriname",
	"urn:li:country:ss": "South Sudan",
	"urn:li:country:st": "Sao Tome and Principe",
	"urn:li:country:sv": "El Salvador",
	"urn:li:country:sy": "Syria",
	"urn:li:country:sz": "Swaziland",
	"urn:li:country:tc": "Turks and Caicos Islands",
	"urn:li:country:td": "Chad",
	"urn:li:country:tf": "French Southern Territories",
	"urn:li:country:tg": "Togo",
	"urn:li:country:th": "Thailand",
	"urn:li:country:tj": "Tajikistan",
	"urn:li:country:tk": "Tokelau",
	"urn:li:country:tl": "Timor-Leste",
	"urn:li:country:tm": "Turkmenistan",
	"urn:li:country:tn": "Tunisia",
	"urn:li:country:to": "Tonga",
	"urn:li:country:tp": "Timor-Leste",
	"urn:li:country:tr": "Turkey",
	"urn:li:country:tt": "Trinidad and Tobago",
	"urn:li:country:tv": "Tuvalu",
	"urn:li:country:tw": "Taiwan",
	"urn:li:country:tz": "Tanzania",
	"urn:li:country:ua": "Ukraine",
	"urn:li:country:ug": "Uganda",
	"urn:li:country:us": "United States",
	"urn:li:country:uy": "Uruguay",
	"urn:li:country:uz": "Uzbekistan",
	"urn:li:country:va": "Vatican City State (Holy See)",
	"urn:li:country:vc": "Saint Vincent and the Grenadines",
	"urn:li:country:ve": "Venezuela",
	"urn:li:country:vg": "Virgin Islands (British)",
	"urn:li:country:vi": "Virgin Islands (U.S.)",
	"urn:li:country:vn": "Vietnam",
	"urn:li:country:vu": "Vanuatu",
	"urn:li:country:wf": "Wallis and Futuna",
	"urn:li:country:ws": "Samoa",
	"urn:li:country:ye": "Yemen",
	"urn:li:country:yt": "Mayotte",
	"urn:li:country:yu": "Yugoslavia",
	"urn:li:country:za": "South Africa",
	"urn:li:country:zm": "Zambia",
	"urn:li:country:zw": "Zimbabwe",
}

// GetSeniorities returns the seniorities map (copy) so caller cannot mutate package var.
func GetSeniorities() map[string]string {
    out := make(map[string]string, len(seniorities))
    for k, v := range seniorities {
        out[k] = v
    }
    return out
}

// GetIndustries returns the industries map.
func GetIndustries() map[string]string {
    out := make(map[string]string, len(industries))
    for k, v := range industries {
        out[k] = v
    }
    return out
}

// GetCountries returns the countries map.
func GetCountries() map[string]string {
    out := make(map[string]string, len(countries))
    for k, v := range countries {
        out[k] = v
    }
    return out
}

// functions maps LinkedIn URNs for job functions to human-readable names.
var functions = map[string]string{
    "urn:li:function:1":  "Accounting",
    "urn:li:function:2":  "Administrative",
    "urn:li:function:3":  "Arts and Design",
    "urn:li:function:4":  "Business Development",
    "urn:li:function:5":  "Community and Social Services",
    "urn:li:function:6":  "Consulting",
    "urn:li:function:7":  "Education",
    "urn:li:function:8":  "Engineering",
    "urn:li:function:9":  "Entrepreneurship",
    "urn:li:function:10": "Finance",
    "urn:li:function:11": "Healthcare Services",
    "urn:li:function:12": "Human Resources",
    "urn:li:function:13": "Information Technology",
    "urn:li:function:14": "Legal",
    "urn:li:function:15": "Marketing",
    "urn:li:function:16": "Media and Communication",
    "urn:li:function:17": "Military and Protective Services",
    "urn:li:function:18": "Operations",
    "urn:li:function:19": "Product Management",
    "urn:li:function:20": "Program and Project Management",
    "urn:li:function:21": "Purchasing",
    "urn:li:function:22": "Quality Assurance",
    "urn:li:function:23": "Real Estate",
    "urn:li:function:24": "Research",
    "urn:li:function:25": "Sales",
    "urn:li:function:26": "Support",
}

// GetFunctions returns the functions map.
func GetFunctions() map[string]string {
    out := make(map[string]string, len(functions))
    for k, v := range functions {
        out[k] = v
    }
    return out
}
