sonar.projectKey=contentstudio-social-analytics-go
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/vendor/**,**/mocks/**,**/mock_*.go,**/mocks_test.go
sonar.go.coverage.reportPaths=src/coverage.out
sonar.go.tests.reportPaths=src/test-report.json
